package com.activitystream.core.model.aspects;

import com.activitystream.core.model.core.AbstractListElement;
import com.activitystream.core.model.interfaces.AspectInterface;
import com.activitystream.core.model.interfaces.BaseStreamElement;

import java.util.List;

public abstract class AbstractListAspect<T> extends AbstractListElement<T> implements AspectInterface {

    boolean autoGenerated = false;

    AbstractListAspect() {
    }

    AbstractListAspect(List values, BaseStreamElement root) {
        super(values, root);
    }

    @Override
    public void mergeAspect(AspectInterface aspect) {

    }

    @Override
    public void markAsAutoGenerated() {
        this.autoGenerated = true;
    }

    @Override
    public boolean isAutoGenerated() {
        return this.autoGenerated;
    }

}
